### ISSUE TITLE
OLED.h missing

### ISSUE THREAD

**Issue by 0Balazs** [kiwih/pic16f877a-ssd1306-oled#1]
Hi I want to use your oled library, but on PIC32MM0256GPM036. When i compile, the mplab give me an error: oled.h missing.

I rewrited the I2C library.

**Comment by kiwih** [comment]
Hi there,

Not sure what's happening here, since none of my files reference an `oled.h`? Have you accidentally included a file that isn't present here?

Also note for use that not all of the files committed here are used by the project.

You might find since your PIC is much more powerful than the PIC16 I was using that you'll get better performance out of a more suitable library! In this repo I have no buffering of graphics, so things like animation and such are not going to work. Indeed, I only really got pixels, texts, and lines working (enough to build simple menus).

**Comment by 0Balazs** [comment]
Sorry I wasn't accurate. "OLED_Display.h" is missing. This is included in "OLED_Display.c".

In the meantime, I found another one that works. Unfortunately, I am struggling with a lack of time so I had to put something together as quickly as possible.

Thanks for sharing the code.

**Comment by kiwih** [comment]
Ah, I see where the confusion is. Actually, OLED_Display.c isn't used in this repository, it was just included for reference purposes. I've moved both it and the _buffered.h version of my header to a folder `/unused` to make it clearer for future explorers.
Glad you got everything worked out!
